"""empty message

Revision ID: 0e514eb5a431
Revises: 37149c2e1ab8
Create Date: 2025-03-26 21:15:12.763360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e514eb5a431'
down_revision = '37149c2e1ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_height_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_height_key', ['height'])

    # ### end Alembic commands ###
