"""empty message

Revision ID: 37149c2e1ab8
Revises: 184420057744
Create Date: 2025-03-26 20:43:15.594773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37149c2e1ab8'
down_revision = '184420057744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
                existing_type=sa.VARCHAR(length=20),
                type_=sa.Integer(),
                existing_nullable=False,
                postgresql_using="height::integer")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
