"""empty message

Revision ID: b708a7ba0deb
Revises: 6cf2cf7c6b87
Create Date: 2025-02-09 23:33:33.327293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b708a7ba0deb'
down_revision = '6cf2cf7c6b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hair_color', sa.String(length=20), nullable=False),
    sa.Column('height', sa.String(length=20), nullable=False),
    sa.Column('skin_color', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('hair_color'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('skin_color')
    )
    op.drop_table('People')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey'),
    sa.UniqueConstraint('gender', name='People_gender_key'),
    sa.UniqueConstraint('hair_color', name='People_hair_color_key'),
    sa.UniqueConstraint('height', name='People_height_key'),
    sa.UniqueConstraint('name', name='People_name_key'),
    sa.UniqueConstraint('skin_color', name='People_skin_color_key')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
